# Generated by Django 5.2.7 on 2026-06-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='networthhistory',
            new_name='conversiona_user_id_a675af_idx',
            old_name='conversionapp_networthhistory_user_timestamp_idx',
        ),
    ]
